params:
  - description: name of the cluster
    name: name
    type: string
  - description: address of the cluster
    name: url
    type: string
  - description: username for basic authentication to the cluster
    name: username
    type: string
  - default: ""
    description: password for basic authentication to the cluster
    name: password
    type: string
  - default: ""
    description: contains PEM-encoded certificate authority certificates
    name: cadata
    type: string
  - default: ""
    description: contains PEM-encoded data from a client key file for TLS
    name: clientKeyData
    type: string
  - default: ""
    description: contains PEM-encoded data from a client cert file for TLS
    name: clientCertificateData
    type: string
  - default: ""
    description: default namespace to use on unspecified requests
    name: namespace
    type: string
  - default: ""
    description: bearer token for authentication to the cluster
    name: token
    type: string
  - default: "false"
    description: to indicate server should be accessed without verifying the TLS certificate
    name: insecure
    type: string
visibility:
  showToUser: true
