params:
  - description: name of the cluster
    name: name
    required: false
    type: 1
    value: ""
  - description: address of the cluster
    name: url
    required: false
    type: 3
    value: ""
  - description: username for basic authentication to the cluster
    name: username
    required: false
    type: 1
    value: ""
  - default: ""
    description: password for basic authentication to the cluster
    name: password
    required: false
    type: 1
    value: ""
  - default: ""
    description: contains PEM-encoded certificate authority certificates
    name: cadata
    required: false
    type: 1
    value: ""
  - default: ""
    description: contains PEM-encoded data from a client key file for TLS
    name: clientKeyData
    required: false
    type: 1
    value: ""
  - default: ""
    description: contains PEM-encoded data from a client cert file for TLS
    name: clientCertificateData
    required: false
    type: 1
    value: ""
  - default: ""
    description: default namespace to use on unspecified requests
    name: namespace
    required: false
    type: 1
    value: ""
  - default: ""
    description: bearer token for authentication to the cluster
    name: token
    required: false
    type: 1
    value: ""
  - default: "false"
    description: to indicate server should be accessed without verifying the TLS certificate
    name: insecure
    required: false
    type: 1
    value: ""
relavancy: 1
visibility:
  showToUser: true
