params:
- description: name of the cluster
  name: name
  type: 1
- description: address of the cluster
  name: url
  type: 1
- description: username for basic authentication to the cluster
  name: username
  type: 1
- default: ''
  description: password for basic authentication to the cluster
  name: password
  type: 1
- default: ''
  description: contains PEM-encoded certificate authority certificates
  name: cadata
  type: 1
- default: ''
  description: contains PEM-encoded data from a client key file for TLS
  name: clientKeyData
  type: 1
- default: ''
  description: contains PEM-encoded data from a client cert file for TLS
  name: clientCertificateData
  type: 1
- default: ''
  description: default namespace to use on unspecified requests
  name: namespace
  type: 1
- default: ''
  description: bearer token for authentication to the cluster
  name: token
  type: 1
- default: 'false'
  description: to indicate server should be accessed without verifying the TLS certificate
  name: insecure
  type: 1
visibility:
  showToUser: true
