---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: flake8
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Code Quality
    tekton.dev/tags: python, flake8, linter
    tekton.dev/displayName: flake8
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This task will run flake8 on the provided input.

  workspaces:
    - name: source
  params:
    - name: path
      description: The path to the module which should be analysed by flake8
      default: "."
      type: string
    - name: requirements_file
      description: The name of the requirements file inside the source location
      default: "requirements.txt"
    - name: args
      description: The arguments to pass to the flake8 CLI.
      type: array
      default: []
  steps:
    - name: flake8
      image: "{{OZONE_PUBLIC_REGISTRY_PREFIX}}/alpine/flake8:3.9"
      workingDir: $(workspaces.source.path)
      script: |
        export HOME=/tmp/python
        export PATH=$PATH:/tmp/python/.local/bin
        if [ -n "$(params.requirements_file)" ] && [ -e "$(params.requirements_file)" ];then
            python -mpip install --user -r $(params.requirements_file)
        fi
        flake8 $@ $(params.path)
      args:
        - $(params.args)
