params:
  - default: api.github.com
    description: "The GitHub host, adjust this if you run a GitHub enterprise.

      "
    name: GITHUB_HOST_URL
    type: string
  - default: ""
    description:
      "The API path prefix, GitHub Enterprise has a prefix e.g. /api/v3

      "
    name: API_PATH_PREFIX
    type: string
  - description: "The GitHub repository full name, i.e: tektoncd/catalog.

      "
    name: REPO_FULL_NAME
    type: string
  - description: "The ref to deploy. This can be a branch, tag, or SHA.

      "
    name: REF
    type: string
  - default: deploy
    description:
      "Specifies a task to execute (e.g., deploy or deploy:migrations).

      "
    name: TASK
    type: string
  - default: "true"
    description: "Attempts to automatically merge the default branch into the

      requested ref, if it's behind the default branch.

      "
    name: AUTO_MERGE
    type: string
  - default: "*"
    description: 'The status contexts to verify against commit status checks. To

      verify all unique contexts before creating a deployment, pass

      in "*". To bypass checking entirely, pass an empty string.

      '
    name: REQUIRED_CONTEXTS
    type: string
  - default: ""
    description: "JSON payload with extra information about the deployment.

      "
    name: PAYLOAD
    type: string
  - description:
      "Name for the target deployment environment (e.g., production, staging).

      "
    name: ENVIRONMENT
    type: string
  - default: ""
    description: "Short description of the deployment.

      "
    name: DESCRIPTION
    type: string
  - default: github
    description:
      "The name of the Kubernetes Secret that contains the GitHub token.

      "
    name: GITHUB_TOKEN_SECRET_NAME
    type: string
  - default: token
    description:
      "The key within the Kubernetes Secret that contains the GitHub token.

      "
    name: GITHUB_TOKEN_SECRET_KEY
    type: string
visibility:
  showToUser: true
