params:
  - default: rox-central-endpoint
    description:
      Name of secret containing the address:port tuple for RHACS Stackrox
      Central.
    name: rox_central_endpoint
    required: false
    type: 1
    value: ""
  - default: rox-api-token
    description: Name of secret containing the RHACS StackRox API token with CI permissions.
    name: rox_api_token
    required: false
    type: 1
    value: ""
  - default: quay.io/stackrox-io/roxctl:3.71.0
    description: Image providing the roxctl tool.
    name: rox_image
    required: false
    type: 1
    value: ""
  - default: $(workspaces.source.path)/deployment.yaml
    description: "Deployment filename to check.

      Examples: 'deployment.yaml', '$(workspaces.source.path)/base/deployment.yaml'

      "
    name: deployment
    required: false
    type: 1
    value: ""
  - default: table
    description: Results output format (csv | json | junit | table)
    name: output_format
    required: false
    type: 1
    value: ""
  - default: "false"
    description: 'Do not verify TLS certificates.


      When set to "true", skip verifying the TLS certs of the Central endpoint and registry.

      '
    name: insecure-skip-tls-verify
    required: false
    type: 1
    value: ""
visibility:
  showToUser: true
