apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
 name: gcs-generic
 labels:
  app.kubernetes.io/version: "0.1"
 annotations:
  tekton.dev/pipelines.minVersion: "0.12.1"
  tekton.dev/categories: Cloud, Storage
  tekton.dev/tags: cloud, gcs
  tekton.dev/platforms: "linux/amd64"
spec:
 description: >-
  A Task that allows users to customize and extend the gsutil
  command line based on their needs.

 workspaces:
 - name: credentials
   description: A secret with a service account key to use as GOOGLE_APPLICATION_CREDENTIALS.
 params:
 - name: command
   description: The command line that you would like to enter.
   type: string
 - name: options
   description: The extended command line that you would like to enter.
   type: array
 - name: serviceAccountPath
   description: |
      The path inside the credentials workspace to the GOOGLE_APPLICATION_CREDENTIALS key file.
   type: string
   default: ''
 steps:
 - name: credential-setup
   image: "{{OZONE_PUBLIC_REGISTRY_PREFIX}}/google.com/cloudsdktool/cloud-sdk:312.0.0-slim"
   script: |
     #!/usr/bin/env bash
     set -xe

      CRED_PATH="$(workspaces.credentials.path)/$(params.serviceAccountPath)"

      if [[ -f "$CRED_PATH" ]]; then
        GOOGLE_APPLICATION_CREDENTIALS="$CRED_PATH"
      fi

      if [[ "${GOOGLE_APPLICATION_CREDENTIALS}" != "" ]]; then
        echo "GOOGLE_APPLICATION_CREDENTIALS is set, activating Service Account..."
        gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS}
      fi
 - name: run-gsutil
   image: "$(params.image)"
   command: [gsutil]
   args: ["$(params.command)", "$(params.options[*])"]
