apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: boskos-acquire
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Cloud
    tekton.dev/tags: "boskos,test"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: |
    Acquire a project using Boskos.

    The boskos-acquire Task will request a resource of the specified type from the
    server-url. If successful, it will start a pod that will run the boskosctl heartbeat
    command. When you are done with the resource, release it with boskos-release.
  params:
  - name: server-url
    description: The URL of the running boskos server
    default: "http://boskos.test-pods.svc.cluster.local"
  - name: type
    description: |
      The type of resource to request. Resource types are specified in the resource
      ConfigMap provided to the Boskos server.
    default: gke-project
  - name: owner-name
    description: A string that identifies the owner of the leased resource to request.
  results:
  - name: leased-resource
    description: The name of the leased resource
  steps:
  - name: boskosctl-acquire
    image: "{{OZONE_PUBLIC_REGISTRY_PREFIX}}/k8s-staging-boskos/boskosctl:v1"
    script: |
      RESOURCE=$(boskosctl acquire \
        --server-url=$(params.server-url) \
        --owner-name=$(params.owner-name) \
        --type=$(params.type) \
        --state=free \
        --target-state=busy)
      echo $RESOURCE > /workspace/full-resource-output.json
      echo $RESOURCE | jq -rj ".name" > /tekton/results/leased-resource
  - name: create-heartbeat-pod-yaml
    image: "{{OZONE_PUBLIC_REGISTRY_PREFIX}}/lachlanevenson/k8s-kubectl:v1.22.16"
    script: |
      FULL_RESOURCE_OUTPUT=$(cat /workspace/full-resource-output.json)
      LEASED_RESOURCE=$(cat /tekton/results/leased-resource)
      cat <<EOF | kubectl apply -f -
      apiVersion: v1
      kind: Pod
      metadata:
        name: boskos-heartbeat-$LEASED_RESOURCE
      spec:
        containers:
        - name: heartbeat
          image: "{{OZONE_PUBLIC_REGISTRY_PREFIX}}/k8s-staging-boskos/boskosctl:v1"
          args:
          - heartbeat
          - --server-url=$(params.server-url)
          - --owner-name=$(params.owner-name)
          - --resource=$FULL_RESOURCE_OUTPUT
          - --period=5m
      EOF