params:
  - description: Prometheus API endpoint
    name: prometheus_endpoint
    required: false
    type: 1
    value: ""
  - description: range query to use to define SLO
    name: range_query
    required: false
    type: 1
    value: ""
  - default: -10m
    description: time we want to assert fits the SLO
    name: range_time
    required: false
    type: 1
    value: ""
  - default: "1"
    description: value we will use as threshold
    name: target_value
    required: false
    type: 1
    value: ""
  - default: min
    description: The target_strategy is min,max or equal
    name: target_strategy
    required: false
    type: 1
    value: ""
  - default: "3600"
    description: timeout of the gate
    name: timeout
    required: false
    type: 1
    value: ""
  - default: 1m
    description: how often to draw data from prometheus
    name: tick_time
    required: false
    type: 1
    value: ""
relavancy: 1
visibility:
  showToUser: true
